configurations:
  - name: helloA
    type: A
    somePropertySpecificToA: hello I am a property of A
  - name: helloB
    type: B
    somePropertySpecificToB: hello I am a property of B

logging.level.root: info
